// PingManager.swift
// Pointward › Managers

import Foundation
import Combine
import os

@MainActor
final class PingManager: ObservableObject {

    private let log = Logger(subsystem: "com.jdcoding75.pointward", category: "pings")

    /// Legacy single-slot ping (still mirrored to the widget store).
    @Published var pendingPing: ReceivedPing?
    @Published var isSending   = false
    /// "Mum felt your thought ✓" — set when a sent ping gets opened remotely.
    @Published var feltNotice: String?
    /// "couldn't send — check your connection" — a real send failed after
    /// retries. The animation already played; the user must know the
    /// thought did NOT travel.
    @Published var sendFailedNotice: String?
    /// "Mum is pointing toward you 🧭" — their compass just locked onto us.
    /// (Toast retired — the ambient presence glow replaced it. Kept.)
    @Published var pointingNotice: String?

    // [9b · B4] partnerPointingAt / partnerPointingName removed with the
    // mutual-pointing cluster (set only by the deleted presenceFelt; read only by the
    // deleted CompassView edge-glow).

    // ── Thought queue ────────────────────────────────────────────────────
    /// Received thoughts waiting to be watched. Max 10; oldest drops off.
    @Published private(set) var queue: [ReceivedPing] = [] {
        didSet {
            queueCount  = queue.count + (nowPlaying == nil ? 0 : 1)
            unreadCount = queueCount
            persistQueue()
        }
    }
    /// The thought currently playing its arrival animation, if any.
    @Published var nowPlaying: ReceivedPing? {
        didSet {
            queueCount  = queue.count + (nowPlaying == nil ? 0 : 1)
            unreadCount = queueCount
        }
    }
    /// Unread thoughts (waiting + the one being caught) — drives the badge.
    @Published var queueCount: Int = 0
    /// QUEUE NOTIFICATION RULE: only the FIRST unread announces itself —
    /// arrivals while this is > 0 slip in silently (badge only). Resets
    /// to 0 automatically when the user catches up (queue drains).
    @Published private(set) var unreadCount: Int = 0

    /// [2/5] LOCAL CAUGHT HISTORY — every thought that's been caught + revealed,
    /// kept on-device so the bucket drawer shows it even when there's no server
    /// row (dev test thoughts) or the network is down. Real thoughts ALSO live
    /// server-side; the drawer dedupes by id. Newest last; capped at 50.
    @Published private(set) var caughtHistory: [ReceivedPing] = [] {
        didSet { persistCaughtHistory() }
    }

    /// [history-split 2026-06] Sent-thought history — newest last, capped 50, persisted
    /// like caughtHistory. Built only by recordSent() at the send site.
    @Published private(set) var sentHistory: [SentRecord] = [] {
        didSet { persistSentHistory() }
    }

    static let maxQueued = 50

    private let networkService: NetworkServiceProtocol

    /// State machine — wired by ServiceContainer. Catch mode and the
    /// caught-confirmation queueing rules flow through here.
    private weak var appState: AppStateManager?

    /// SENDER CAUGHT — the recipient caught our thought. The emoji we sent
    /// reappears briefly at the compass center. No text, no timestamp.
    struct CaughtMoment: Equatable {
        let emoji: String
        let at:    Date
    }
    @Published var caughtMoment: CaughtMoment?

    struct ReceivedPing: Equatable, Identifiable {
        let id = UUID()
        let fromName:  String
        let emoji:     String
        let timestamp: Date
        var remoteID:  UUID? = nil      // Supabase ping id, for read receipts
        /// sender_style from the wire — the SENDER's animation personality.
        /// nil (pre-migration rows) falls back to glow at the call site.
        var senderStyle: String? = nil
        /// [5/5] Optional short message (≤30 chars) the sender attached.
        var message: String? = nil
        /// The sender's per-person tagline, travelling with the thought.
        var tagline: String? = nil
        /// [2/5] DEBUG: marks a thought generated by the developer test tools
        /// so "clear test thoughts" can remove only these, never real ones.
        var isTest: Bool = false
    }

    /// [history-split 2026-06] A thought the USER sent — the sent-side mirror of
    /// ReceivedPing, for the "thoughts sent ✦" bucket section. Display-only (no
    /// remoteID/read-receipt, no isTest: the demo path never records a sent thought).
    struct SentRecord: Equatable, Identifiable {
        let id = UUID()
        let toName:      String
        let emoji:       String
        let timestamp:   Date
        var senderStyle: String? = nil
        var message:     String? = nil
        var tagline:     String? = nil
    }

    init(networkService: NetworkServiceProtocol, appState: AppStateManager? = nil) {
        self.networkService = networkService
        self.appState = appState
        restoreQueue()          // waiting thoughts survive an app relaunch
        restoreCaughtHistory()  // [2/5] caught-thought history survives too
        restoreSentHistory()    // [history-split 2026-06] sent-thought history survives too
    }

    static let maxCaughtHistory = 50

    /// [2/5] Record a thought as caught + revealed so it appears in the bucket
    /// drawer — works for real AND dev test thoughts, the latter having no
    /// server row. Idempotent by id (a re-reveal never duplicates).
    func recordCaught(_ ping: ReceivedPing) {
        if let id = ping.remoteID, caughtHistory.contains(where: { $0.remoteID == id }) { return }
        if caughtHistory.contains(where: { $0.id == ping.id }) { return }
        var updated = caughtHistory
        updated.append(ping)
        if updated.count > Self.maxCaughtHistory {
            updated.removeFirst(updated.count - Self.maxCaughtHistory)
        }
        caughtHistory = updated
        log.info("history: recorded caught thought from \(ping.fromName, privacy: .public) (\(self.caughtHistory.count) kept)")
    }

    /// [history-split 2026-06] Append a sent thought (newest last; cap maxCaughtHistory).
    /// No id/remoteID dedup — every send is a distinct event.
    func recordSent(_ record: SentRecord) {
        var updated = sentHistory
        updated.append(record)
        if updated.count > Self.maxCaughtHistory {
            updated.removeFirst(updated.count - Self.maxCaughtHistory)
        }
        sentHistory = updated
        log.info("history: recorded sent thought to \(record.toName, privacy: .public) (\(self.sentHistory.count) kept)")
    }

    /// [bucket delete · ⭐ Phase-3 backbone] Remove ONE thought from local history by its
    /// BUCKET id — the value the bucket/replay carries, which is `remoteID ?? id` (matches
    /// how `loadCompassThoughts` keys each PingRecord). Idempotent: a no-op if absent.
    /// `caughtHistory`'s didSet re-persists automatically (current UserDefaults shape;
    /// NO schema/preserved-flag change). This is the SINGLE per-item remove for
    /// caughtHistory — the future History-tab swipe-delete reuses it.
    func removeFromHistory(id: UUID) {
        let before = caughtHistory.count
        caughtHistory.removeAll { ($0.remoteID ?? $0.id) == id }
        if caughtHistory.count != before {
            log.info("history: removed 1 thought (\(self.caughtHistory.count) kept)")
        }
    }

    private func persistCaughtHistory() {
        let stored = caughtHistory.map {
            PersistedPing(fromName: $0.fromName, emoji: $0.emoji,
                          timestamp: $0.timestamp, remoteID: $0.remoteID,
                          senderStyle: $0.senderStyle, message: $0.message,
                          tagline: $0.tagline, isTest: $0.isTest)
        }
        if let data = try? JSONEncoder().encode(stored) {
            UserDefaults.standard.set(data, forKey: "caughtHistory")
        }
    }

    private func restoreCaughtHistory() {
        guard let data = UserDefaults.standard.data(forKey: "caughtHistory"),
              let stored = try? JSONDecoder().decode([PersistedPing].self, from: data),
              !stored.isEmpty else { return }
        caughtHistory = stored.map {
            ReceivedPing(fromName: $0.fromName, emoji: $0.emoji,
                         timestamp: $0.timestamp, remoteID: $0.remoteID,
                         senderStyle: $0.senderStyle, message: $0.message,
                         tagline: $0.tagline, isTest: $0.isTest)
        }
    }

    // ── [history-split 2026-06] Sent-thought persistence (new "sentHistory" key) ──
    private struct PersistedSent: Codable {
        let toName: String
        let emoji: String
        let timestamp: Date
        var senderStyle: String? = nil
        var message: String? = nil
        var tagline: String? = nil
    }

    private func persistSentHistory() {
        let stored = sentHistory.map {
            PersistedSent(toName: $0.toName, emoji: $0.emoji, timestamp: $0.timestamp,
                          senderStyle: $0.senderStyle, message: $0.message, tagline: $0.tagline)
        }
        if let data = try? JSONEncoder().encode(stored) {
            UserDefaults.standard.set(data, forKey: "sentHistory")
        }
    }

    private func restoreSentHistory() {
        guard let data = UserDefaults.standard.data(forKey: "sentHistory"),
              let stored = try? JSONDecoder().decode([PersistedSent].self, from: data),
              !stored.isEmpty else { return }
        sentHistory = stored.map {
            SentRecord(toName: $0.toName, emoji: $0.emoji, timestamp: $0.timestamp,
                       senderStyle: $0.senderStyle, message: $0.message, tagline: $0.tagline)
        }
    }

    // ── Queue persistence — unread thoughts survive relaunches ──────────

    private struct PersistedPing: Codable {
        let fromName: String
        let emoji: String
        let timestamp: Date
        let remoteID: UUID?
        let senderStyle: String?
        var message: String? = nil
        var tagline: String? = nil
        var isTest: Bool = false
    }

    private func persistQueue() {
        let stored = queue.map {
            PersistedPing(fromName: $0.fromName, emoji: $0.emoji,
                          timestamp: $0.timestamp, remoteID: $0.remoteID,
                          senderStyle: $0.senderStyle, message: $0.message,
                          tagline: $0.tagline, isTest: $0.isTest)
        }
        if let data = try? JSONEncoder().encode(stored) {
            UserDefaults.standard.set(data, forKey: "pendingThoughtQueue")
        }
    }

    private func restoreQueue() {
        guard let data = UserDefaults.standard.data(forKey: "pendingThoughtQueue"),
              let stored = try? JSONDecoder().decode([PersistedPing].self, from: data),
              !stored.isEmpty else { return }
        log.info("queue: restored \(stored.count) waiting thought(s) from last session")
        queue = stored.map {
            ReceivedPing(fromName: $0.fromName, emoji: $0.emoji,
                         timestamp: $0.timestamp, remoteID: $0.remoteID,
                         senderStyle: $0.senderStyle, message: $0.message,
                         tagline: $0.tagline, isTest: $0.isTest)
        }
    }

    #if DEBUG
    /// [2/5] Remove only developer-generated test thoughts from the bucket
    /// queue (and a test thought currently being caught). Real thoughts —
    /// anything that ever arrived from a partner — are left untouched.
    func clearTestThoughts() {
        queue.removeAll { $0.isTest }
        caughtHistory.removeAll { $0.isTest }   // [2/5] also drop test thoughts from history
        if nowPlaying?.isTest == true {
            nowPlaying = nil
            AppGroupStore.clearPendingPing()
        }
        log.info("DEV: cleared test thoughts — \(self.queue.count) real thought(s) kept")
    }

    /// [4/5] Wipe ALL local thought state — the bucket queue, the one being
    /// caught, the widget mirror, and the "seen" ledger. Part of the surgical
    /// "clear all my data" flow (user data only).
    func clearAllThoughts() {
        queue.removeAll()
        caughtHistory.removeAll()   // [2/5] history is local user data — wipe it too
        nowPlaying = nil
        pendingPing = nil
        AppGroupStore.clearPendingPing()
        UserDefaults.standard.removeObject(forKey: "seenPingIDs")
        UserDefaults.standard.removeObject(forKey: "pendingThoughtQueue")
        UserDefaults.standard.removeObject(forKey: "caughtHistory")
        log.info("DEV: cleared ALL local thoughts")
    }
    #endif

    // ── Offline catch queue — thoughts that arrived while we were away ──
    //
    // Realtime and pushes both miss when the app is offline; the pings are
    // safe in Supabase. On every foreground/reconnect we sweep for unread
    // ones we've never SEEN: the newest becomes the catch, the rest stay in
    // History (they're already there server-side). No error states — quiet
    // either way.

    /// Ping ids that ever entered the local queue — so offline sweeps never
    /// re-trigger a catch for something already offered. Capped at 50. [3/6]
    private var seenPingIDs: [String] {
        get { UserDefaults.standard.stringArray(forKey: "seenPingIDs") ?? [] }
        set { UserDefaults.standard.set(Array(newValue.suffix(50)), forKey: "seenPingIDs") }
    }

    private func rememberSeen(_ id: UUID?) {
        guard let id else { return }
        var seen = seenPingIDs
        guard !seen.contains(id.uuidString) else { return }
        seen.append(id.uuidString)
        seenPingIDs = seen
    }

    /// Sweep one partner's pings for unread thoughts that never reached
    /// this device. `resolveName` maps the partner id to their card name.
    func syncMissedThoughts(partnerID: UUID, partnerName: String) async {
        let records = await SupabaseService.shared.fetchPings(with: partnerID)
        let me = SupabaseService.localUserID
        let seen = Set(seenPingIDs)
        // Unread, addressed to me, never seen here — oldest…newest
        let missed = records
            .filter { record in
                record.openedAt == nil
                    && record.toUser.uuidString == me?.uuidString
                    && !seen.contains(record.id.uuidString)
            }
            .sorted { $0.createdAt < $1.createdAt }
        guard !missed.isEmpty else { return }
        log.info("offline-sync: \(missed.count) missed thought(s) from \(partnerName, privacy: .public)")

        // All are remembered as seen; only the NEWEST goes through the
        // queue → catch. Older ones rest in History (already server-side).
        for record in missed { rememberSeen(record.id) }
        if let newest = missed.last {
            receivePing(fromName: partnerName, emoji: newest.emoji,
                        remoteID: newest.id, senderStyle: newest.senderStyle,
                        message: newest.message, tagline: newest.tagline)
        }
    }

    func sendPing(to person: Person, emoji: String) async {
        isSending = true
        defer { isSending = false }
        let pairedID = person.pairedUserID ?? "local-stub"
        // The real Supabase insert (SupabaseService.sendPing) carries
        // sender_style = SenderStyle.effectiveForCurrentUser; this legacy
        // mock path stays style-less.
        try? await networkService.sendPing(toPairedUserID: pairedID, emoji: emoji)
        HapticEngine.pingSent()
    }

    /// THE real send. Fires the Supabase insert (with its own retry layer)
    /// and — critically — surfaces failure instead of swallowing it: the
    /// flight animation plays optimistically, but if the insert never lands
    /// the user is told their thought did not travel.
    func sendRemote(to userID: UUID, emoji: String, style: SenderStyle,
                    message: String? = nil, tagline: String? = nil) {
        log.info("sendRemote: → \(userID.uuidString, privacy: .public) emoji=\(emoji, privacy: .public) style=\(style.rawValue, privacy: .public) msg=\(message != nil, privacy: .public) tag=\(tagline != nil, privacy: .public)")
        Task {
            do {
                try await SupabaseService.shared.sendPing(to: userID, emoji: emoji, style: style, message: message, tagline: tagline)
                log.info("sendRemote: delivered ✓")
            } catch {
                log.error("sendRemote: FAILED — \(error.localizedDescription, privacy: .public)")
                sendFailedNotice = "couldn't send — check your connection"
                try? await Task.sleep(nanoseconds: 4_000_000_000)
                sendFailedNotice = nil
            }
        }
    }

    // ════════════════════════════════════════════════════════════════════
    // [phase2 stage A] LINK-BASED SEND — LIVE (un-gated; PATH-2 "a link for everyone")
    // ════════════════════════════════════════════════════════════════════
    // The Build-3 `#if DEBUG` guardrail ("/m/ links aren't openable until Build 4")
    // is obsolete — links open since 4a, the web page is live, and the legacy
    // sendRemote double-send is removed. This is now the live release send path.
    // It NEVER auto-shares (the user picks the destination in the share sheet).

    /// "couldn't create your link — retry" — the message insert failed. The
    /// animation already played (sacred); this is a quiet, non-blocking notice
    /// with a retry that re-runs the insert.
    @Published var linkFailedNotice: String?
    private var lastLinkSend: (() -> Void)?

    // [#1 share-on-animation-complete] The share sheet must appear only AFTER the send
    // animation finishes — not the instant the insert returns (which lands mid-flight,
    // cutting the animation off). createAndShareLink stashes the built share text here
    // instead of presenting; the View calls markSendAnimationComplete() from finishSend
    // (every send-out animation's terminal funnel). Whichever lands second presents.
    private var pendingShareText: String?
    private var sendAnimationComplete = false

    /// Store the just-sent thought as a `messages` row, then present the share
    /// sheet with the /m/[id] link + the short-code fallback. Background work —
    /// the caller has already kicked off the (uninterrupted) send animation.
    /// `onStored` fires with the new message id once the insert succeeds — the
    /// caller records the (S1) SentLink (messageID → local contact) so Stage B/C
    /// can stamp the right contact. (PingManager has no ModelContext by design;
    /// the SwiftData write lives in PeopleManager.)
    func createAndShareLink(content: String?, emoji: String, instrument: String,
                            senderName: String, shortCode: String,
                            personID: UUID? = nil,
                            onStored: ((UUID) -> Void)? = nil) {
        let run: () -> Void = { [weak self] in
            guard let self else { return }
            self.linkFailedNotice = nil
            // [#1] New send → clear any prior link-ready / animation-done coordination so
            // THIS send's sheet waits for THIS send's animation to finish (runs
            // synchronously, before the animation can complete).
            self.pendingShareText = nil
            self.sendAnimationComplete = false
            Task { @MainActor in
                do {
                    let id = try await SupabaseService.shared.insertMessage(
                        content: content, emoji: emoji, instrument: instrument,
                        senderDisplayName: senderName.isEmpty ? nil : senderName)
                    // (S1) record the sent-link → contact mapping (if a contact was attached).
                    if personID != nil { onStored?(id) }
                    let link = MessageLink.url(for: id)
                    let text = MessageLink.shareText(senderName: senderName,
                                                     link: link, shortCode: shortCode)
                    self.log.info("link: message stored (id=\(id.uuidString, privacy: .public)) — sharing once the send animation completes")
                    // [#1] Stash the built link; present only once the send animation has
                    // finished (markSendAnimationComplete). Whichever lands second wins.
                    self.pendingShareText = text
                    self.presentShareIfReady()
                } catch {
                    self.log.error("link: insert FAILED — \(error.localizedDescription, privacy: .public)")
                    self.linkFailedNotice = "couldn't create your link — retry"
                }
            }
        }
        lastLinkSend = run
        run()
    }

    /// Re-run the last link send (the retry affordance on linkFailedNotice).
    func retryLinkSend() { lastLinkSend?() }

    /// [#1] Called by the View when the send animation completes (CompassView.finishSend —
    /// the single terminal funnel for all send-out onComplete closures). If the link is
    /// already built, present now; otherwise the insert-completion will present it.
    func markSendAnimationComplete() {
        sendAnimationComplete = true
        presentShareIfReady()
    }

    /// [#1] Present the share sheet only when BOTH the link is built AND the send animation
    /// has finished. Idempotent — clears the state after presenting so it fires exactly once.
    private func presentShareIfReady() {
        guard sendAnimationComplete, let text = pendingShareText else { return }
        pendingShareText = nil
        sendAnimationComplete = false
        ShareSheet.present(text)
    }

    func showFelt(name: String) {
        feltNotice = "\(name) felt your thought ✓"
        Task {
            try? await Task.sleep(nanoseconds: 3_500_000_000)
            feltNotice = nil
        }
    }

    /// They caught it. A warm symbolic moment on the sender's compass —
    /// the emoji we sent, briefly, then gone. Never interrupts sending
    /// (or any other moment): it queues and plays when the screen is free.
    func showCaught(emoji: String) {
        let show: () -> Void = { [weak self] in
            guard let self else { return }
            self.caughtMoment = CaughtMoment(emoji: emoji, at: .now)
            Task {
                try? await Task.sleep(nanoseconds: 900_000_000)   // 600 ms + fade
                self.caughtMoment = nil
            }
        }
        if let appState, appState.currentState != .idle {
            appState.queueAnimation(show)
        } else {
            show()
        }
    }

    /// Gentle "they're pointing at you" moment — soft double haptic, 4s toast.
    func showPointing(name: String) {
        // [2/6] Ambient presence is always on now — no setting gate.
        pointingNotice = "\(name) is pointing toward you"
        HapticEngine.pingReceived()
        Task {
            try? await Task.sleep(nanoseconds: 4_000_000_000)
            pointingNotice = nil
        }
    }

    /// New thought arrives → catch mode. RULE: only the NEWEST incoming
    /// thought triggers the catch — anything older slips quietly into
    /// History (it's already persisted server-side in the pings table).
    func receivePing(fromName: String, emoji: String, remoteID: UUID? = nil,
                     senderStyle: String? = nil, message: String? = nil,
                     tagline: String? = nil, isTest: Bool = false,
                     autoPlay: Bool = true) {
        log.info("receivePing: from=\(fromName, privacy: .public) emoji=\(emoji, privacy: .public) remoteID=\(remoteID?.uuidString ?? "nil", privacy: .public) style=\(senderStyle ?? "nil", privacy: .public)")

        // DEDUPE: in the foreground the same thought arrives twice — once
        // over realtime (with remoteID) and once as the APNs push (without).
        // Same id, or same emoji+sender within 15 s → one catch, not two.
        // [3/6] DEV test thoughts are EXEMPT — sending the same emoji to
        // yourself twice in a row must always play, never silently de-dupe.
        let isDuplicate = !isTest && ([nowPlaying].compactMap { $0 } + queue).contains { existing in
            if let id = remoteID, existing.remoteID == id { return true }
            return existing.emoji == emoji
                && existing.fromName == fromName
                && Date.now.timeIntervalSince(existing.timestamp) < 15
        }
        if isDuplicate {
            log.info("receivePing: duplicate (realtime + push) — ignored")
            return
        }

        // QUEUE NOTIFICATION RULE: only the FIRST unread thought announces
        // itself. While one is already waiting, newcomers slip in silently —
        // no haptic, no fanfare; the badge count is the only change.
        let isFirstUnread = unreadCount == 0

        let ping = ReceivedPing(fromName: fromName, emoji: emoji, timestamp: .now,
                                remoteID: remoteID, senderStyle: senderStyle,
                                message: message, tagline: tagline, isTest: isTest)
        // MULTI-SENDER QUEUE: an active catch is NEVER interrupted, and
        // waiting thoughts are ALL kept — each with its own sender name and
        // style, so every later catch and replay is correctly attributed.
        // Oldest drops past 10 (it lives in History server-side anyway).
        var updated = queue
        updated.append(ping)
        if updated.count > Self.maxQueued {
            updated.removeFirst(updated.count - Self.maxQueued)
        }
        queue = updated
        rememberSeen(remoteID)
        AppGroupStore.pendingPingEmoji     = emoji
        AppGroupStore.pendingPingFromName  = fromName
        AppGroupStore.pendingPingTimestamp = .now
        if isFirstUnread && appState?.currentState != .sending {
            HapticEngine.thoughtArrived()   // soft directional pull, not an alert
        } else {
            log.info("receivePing: arrived silently (badge only) — first unread already waiting, or a send is in progress")
        }

        // A catch already on screen finishes its moment; anything else
        // waits on the badge and plays when the user taps for it.
        //
        // [3/6] BUG FIX — the auto-play gate used to be `queue.count == 1`,
        // so when ANY thought was already waiting in the bucket (e.g. a
        // restored offline thought, or a previous dev test), a freshly sent
        // "test thought to myself" would land silently and NEVER open the
        // receipt. The correct gate is "nothing is currently on screen": if
        // the screen is free, open the next thought. A DEV test thought is
        // always honoured immediately — it jumps the queue so the developer
        // sees the full receipt every time, even behind older waiting ones.
        // [5/5] autoPlay:false queues the thought silently for later (used by
        // "Test All Animations" so all 7 stack in the bucket, then "Auto-catch
        // all" plays them in sequence).
        if autoPlay && nowPlaying == nil {
            if appState?.currentState == .sending {
                // [2/5] SIMULTANEOUS SEND/RECEIVE — never let an arriving
                // thought interrupt a send in progress. While sending it sits
                // in the queue (badge only); the catch fires the instant the
                // send completes (the screen returns to idle and drains).
                log.info("receivePing: send in progress — queued, catch will play when the send completes")
                appState?.queueAnimation { [weak self] in self?.playNext() }
            } else if isTest, let idx = queue.firstIndex(where: { $0.id == ping.id }) {
                // DEV test thought jumps straight to the front of an idle screen.
                nowPlaying = queue.remove(at: idx)
            } else {
                // [live-arrival-fix] Start the FIRST thought whenever the screen is idle (nowPlaying == nil),
                // not only when it's the LONE queued item. A burst queues behind it; the user advances with
                // Next. While a thought rests, nowPlaying stays non-nil → new arrivals just queue.
                playNext()
            }
        }
    }

    /// Start (or skip to) the next queued thought.
    /// opened_at is set at the moment of REVEAL (markOpened), not here —
    /// "felt" means felt, not delivered.
    func playNext() {
        guard !queue.isEmpty else {
            nowPlaying = nil
            return
        }
        nowPlaying = queue.removeFirst()
    }

    /// The thought was actually experienced — bloom played, sound heard.
    func markOpened(_ ping: ReceivedPing) {
        // [2/5] Save it to local history the moment it's revealed, so the bucket
        // drawer shows it — test thoughts included (they have no server row).
        recordCaught(ping)
        if let remoteID = ping.remoteID {
            log.info("markOpened: id=\(remoteID.uuidString, privacy: .public)")
            Task { await SupabaseService.shared.markPingOpened(remoteID) }
        } else {
            // Push-delivered pings used to arrive without an id — the felt
            // receipt was silently lost. The push payload now carries pingId.
            log.warning("markOpened: no remoteID — felt receipt cannot be recorded")
        }
    }

    // [9b · B4] presenceFelt removed — its only caller was NotificationHandler's dead
    // "pointing" branch; it set the mutual-pointing state (also removed).

    // ── Replay, app-wide ─────────────────────────────────────────────────
    /// Set from any tab; RootView presents the full-screen replay overlay.
    struct ReplayItem: Identifiable, Equatable {
        let id = UUID()
        let emoji: String
        let bearingDegrees: Double
        let styleRaw: String?
        var fromName: String = ""
        // AUDIT [5/6]: the note + tagline travel with the thought; carry them
        // into replay so a replayed thought shows everything the live catch did.
        var message: String? = nil
        var tagline: String? = nil
        // [bucket delete] The caughtHistory BUCKET id (`remoteID ?? id`) this replay
        // item came from, so the overlay's Delete can remove THE RIGHT history item.
        // nil for replays that don't originate from the bucket (no Delete shown).
        var historyID: UUID? = nil
    }
    struct ReplayRequest: Identifiable, Equatable {
        let id = UUID()
        let emoji: String
        let bearingDegrees: Double
        let styleRaw: String?
        var fromName: String = ""
        var message: String? = nil
        var tagline: String? = nil
        // The full list this replay belongs to + our position, so the overlay
        // can SWIPE to the next/previous thought without re-presenting.
        var siblings: [ReplayItem] = []
        var index: Int = 0
        // [bucket delete] Bucket id for the SINGLE-item fallback (siblings empty);
        // multi-item replays carry it per-sibling on each ReplayItem instead.
        var historyID: UUID? = nil
    }
    @Published var replayRequest: ReplayRequest?

    func requestReplay(emoji: String, bearingDegrees: Double, styleRaw: String?,
                       fromName: String = "", message: String? = nil, tagline: String? = nil) {
        log.info("replay: requested — \(emoji, privacy: .public) bearing=\(Int(bearingDegrees), privacy: .public)°")
        replayRequest = ReplayRequest(emoji: emoji, bearingDegrees: bearingDegrees,
                                      styleRaw: styleRaw, fromName: fromName,
                                      message: message, tagline: tagline)
    }

    /// Replay a whole list, starting at `startIndex` — the overlay can swipe
    /// between the thoughts.
    func requestReplaySequence(_ items: [ReplayItem], startIndex: Int) {
        guard !items.isEmpty else { return }
        let i = max(0, min(items.count - 1, startIndex))
        let it = items[i]
        replayRequest = ReplayRequest(emoji: it.emoji, bearingDegrees: it.bearingDegrees,
                                      styleRaw: it.styleRaw, fromName: it.fromName,
                                      message: it.message, tagline: it.tagline,
                                      siblings: items, index: i,
                                      historyID: it.historyID)   // [bucket delete] start item's id (single-fallback)
    }

    // ── Felt receipts, live ──────────────────────────────────────────────
    /// Bumped whenever one of OUR sent pings gets opened — history views
    /// listening to this refetch and flip their dot to "felt".
    @Published var lastFeltAt: Date?

    // [9b · B4] Mutual-pointing cluster REMOVED — partnerPointingBearing, mutualMoment,
    // lastMutualMoment, and checkMutualPointing (the latter had NO live caller; the
    // RootView triggers were already commented). The source (reportPointing) was a no-op,
    // so none of this ever fired. (lastFeltAt above is the LIVE felt-receipt stream — kept.)

    /// Called when an arrival animation completes. Waiting thoughts do NOT
    /// auto-play — the badge shows the count and the user taps to catch the
    /// next when ready. (previous: auto-advance after 2 s — retired)
    func finishedPlaying(_ ping: ReceivedPing) {
        guard nowPlaying?.id == ping.id else { return }
        nowPlaying = nil
        AppGroupStore.clearPendingPing()
        // [4/5] AUTO-CATCH — when draining the bucket automatically, pause 2 s
        // then catch the next thought; stop when the bucket is empty.
        if isAutoCatching {
            if queue.isEmpty {
                isAutoCatching = false
                log.info("auto-catch: bucket drained ✓")
            } else {
                DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) { [weak self] in
                    guard let self, self.isAutoCatching else { return }
                    self.playNext()
                }
            }
            return
        }
        if !queue.isEmpty {
            log.info("queue: \(self.queue.count) thought(s) waiting — badge shows, user taps to catch")
        }
    }

    /// [4/5] DEBUG auto-catch — drains the entire bucket, auto-aligning and
    /// playing each receipt in turn (ReceiptView watches `isAutoCatching` to
    /// auto-lock and auto-advance), with a 2 s pause between thoughts. The flag
    /// itself compiles in all builds but is only ever set from Developer Tools.
    @Published var isAutoCatching = false

    func startAutoCatch() {
        guard nowPlaying != nil || !queue.isEmpty else {
            log.info("auto-catch: nothing in the bucket")
            return
        }
        log.info("auto-catch: starting — \(self.queue.count + (self.nowPlaying == nil ? 0 : 1)) thought(s)")
        isAutoCatching = true
        if nowPlaying == nil { playNext() }
    }

    /// Tap-to-skip: jump straight to the next thought, no 2-second gap.
    func skip(_ ping: ReceivedPing) {
        guard nowPlaying?.id == ping.id else { return }
        nowPlaying = nil
        AppGroupStore.clearPendingPing()
        playNext()
    }

    func clearPendingPing() {
        pendingPing = nil
        AppGroupStore.clearPendingPing()
    }
}

// ── Message rules — the optional ≤30-char note that rides a thought ───────
// Pure + testable, so the same clamping/normalizing runs in the compose UI
// (CompassView) and the send path (SupabaseService.sendPing).
enum MessageRules {
    static let maxLength = 30

    /// Trim a message to the maximum length (the compose field uses this).
    static func clamped(_ message: String) -> String {
        String(message.prefix(maxLength))
    }

    /// Normalize for sending: an empty/whitespace-only message becomes nil so
    /// it's omitted from the payload entirely; otherwise it's clamped.
    static func normalized(_ message: String?) -> String? {
        guard let message else { return nil }
        let trimmed = message.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : clamped(trimmed)
    }
}
